ARTICLE_STATUS_DRAFT = "draft"
ARTICLE_STATUS_PUBLISHED = "published"
ARTICLE_STATUS_ARCHIVED = "archived"

SUBMISSION_STATUS_NEW = "new"
SUBMISSION_STATUS_REVIEWING = "reviewing"
SUBMISSION_STATUS_ACCEPTED = "accepted"
SUBMISSION_STATUS_REJECTED = "rejected"
